/* eslint-disable jsx-a11y/anchor-is-valid */
import Head from 'next/head';
import Link from 'next/link';
import Footer from '../components/footer';
import Portfolio from '../components/portfolio';
import Blogs from '../components/blog';
import Navbar from '../components/navbar';

export default function Home() {
  return (
    <>
      <div className="mx-auto max-w-7xl px-4 space-y-8 sm:px-6 lg:px-8">
        <Head>
          <title>Simple Blog Reeyyy</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* Navbar Starts */}
        <Navbar />
        {/* Navbar Ends */}

        <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
          <h2 className="text-2xl font-bold tracking-tight text-gray-900">
            Newest Blogs
            <Link legacyBehavior href="/blogs">
              <a className="text-sm ml-1 text-indigo-600">(See All)</a>
            </Link>
          </h2>

          {/* Blog List Starts */}
          <Blogs />
          {/* Blog List Ends */}

          <br />

          <h2 className="text-2xl font-bold tracking-tight text-gray-900">
            Portfolios
            <Link legacyBehavior href="/portfolios">
              <a className="text-sm ml-1 text-indigo-600">(See All)</a>
            </Link>
          </h2>

          {/* Portfolio List Starts */}
          <Portfolio />
          {/* Portfolio List Ends */}
        </div>
      </div>

      <Footer />
    </>
  );
}
